spring.application.name=cidades-esg-inteligentes-prod
app.environment=production
server.port=${PORT:8080}
spring.data.mongodb.uri=${MONGODB_URI:mongodb://mongodb-prod:27017/cidades_esg_prod}
logging.level.br.com.fiap.cidadesesg=WARN
