spring.application.name=cidades-esg-inteligentes-staging
app.environment=staging
server.port=${PORT:8081}
spring.data.mongodb.uri=${MONGODB_URI:mongodb://mongodb-staging:27017/cidades_esg_staging}
logging.level.br.com.fiap.cidadesesg=DEBUG
