apiVersion: v1
kind: ConfigMap
metadata:
  name: esg-api-config
  namespace: staging
data:
  APP_ENVIRONMENT: "staging"
  PORT: "8080"
  SPRING_PROFILES_ACTIVE: "staging"
---
apiVersion: v1
kind: Secret
metadata:
  name: esg-api-secret
  namespace: staging
type: Opaque
data:
  # mongodb://staging_user:staging_pass@mongodb-service.staging.svc.cluster.local:27017/cidades_esg_staging?authSource=admin
  MONGODB_URI: bW9uZ29kYjovL3N0YWdpbmdfdXNlcjpzdGFnaW5nX3Bhc3NAbW9uZ29kYi1zZXJ2aWNlLnN0YWdpbmcuc3ZjLmNsdXN0ZXIubG9jYWw6MjcwMTcvY2lkYWRlc19lc2dfc3RhZ2luZz9hdXRoU291cmNlPWFkbWlu
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: esg-api-config
  namespace: production
data:
  APP_ENVIRONMENT: "production"
  PORT: "8080"
  SPRING_PROFILES_ACTIVE: "prod"
---
apiVersion: v1
kind: Secret
metadata:
  name: esg-api-secret
  namespace: production
type: Opaque
data:
  # mongodb://prod_user:prod_secure_pass@mongodb-service.production.svc.cluster.local:27017/cidades_esg_prod?authSource=admin
  MONGODB_URI: bW9uZ29kYjovL3Byb2RfdXNlcjpwcm9kX3NlY3VyZV9wYXNzQG1vbmdvZGItc2VydmljZS5wcm9kdWN0aW9uLnN2Yy5jbHVzdGVyLmxvY2FsOjI3MDE3L2NpZGFkZXNfZXNnX3Byb2Q/YXV0aFNvdXJjZT1hZG1pbg==
